language: node_js

node_js:
    - "6"

deploy:
    provider: heroku
    api_key:
        secure: Rv1hVVDSJPS3niI1mJkxqvRuNUMnSuNrnkxPr2BNa+lH74WJABEqWzwqWWgRTcMtozkfcsDlfi7AGCexnyiUOCDmflLPqXZV4Yr7PYUzpUbxOE2pMkL0+wdcUzo9nlAlixqFJD9WjMXi9/dQGs7/C199uXc3SEcLvps44ldGqRbU8Izq7OYRJtG2brM4195HDIC0f9+dEM8Lg+p7ZwJe0NrvrMJS4sk2xeCMVgYT3kfr7p7RA2NjdRdEj88B+RuN5G9XGG58yNbdIZK5eOk1eaTzJ67r+by2CcqzHndTiPFD2uwf8lGgUwziJ5+m3Nec3Lj1JGKUoj70vAgiBZC1xTVPmgqehrYp6tS9OXCw4iCLgbD01L9tPelYNDZFSvcY5dxbuGgeUL95+3+72+9AP5ra626xIow7MCrYdsdDEIB43Ml3MFSPC2gkWV6uSsE/zdAoVEnI3ayzP1XyUbNehmPng8NWq+CRrq0S6jXzyuSHIHoy+v2EYt5b0/buz/Z0JnVcvZ6rh4sWoDyhG2AFr/izpY35+LkH9aKg0ZOXBCGv4ILE0lsIjiW1Kr60C6sPxPqN7Beo/fkvas6or3YrwD4R8ps+YZBwa+LJxS+O+mdp0kJrfmM/Q+Kb2HUTjO53AoYosIY7X4lE4uXrkn8LyHcvzJRvufxhwEEjQ6UftVo=
    app: team1
